version: '3.11.2'

services:
  # db_mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: mydatabase

  db_postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/code
    ports:
      - "8000:8000"
    depends_on:
      #- db_mysql
      - db_postgres

volumes:
  # mysql_data:
  postgres_data:
